# .readthedocs.yaml
# Read the Docs configuration file for Sphinx documentation
# See: https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

# Tell Read the Docs where your Sphinx conf.py lives
sphinx:
  configuration: source/conf.py # or docs/conf.py — adjust if needed

# Install dependencies required to build the docs
python:
  install:
    - requirements: requirements.txt # Install Sphinx + theme only

# Optional: build additional formats for download
formats:
  - htmlzip
  - pdf
  - epub
