Welcome to TPA Stream! Here you'll find comprehensive information for linking your application with the TPA Stream API, allowing you to focus on building your product, not integrating with ours. If you're planning to use our API in Production, please review our `Privacy Policy <https://app.tpastream.com/privacy>`_.

TPA Stream's developer tools consist of a **JavaScript SDK** Client Library to embed consumer enrollment into your web or mobile application, **Webhooks** to provide your application with realtime Claim updates, and a **REST API** for getting the most up-to-date information.
